### ISSUE TITLE
"pause" command not available on linux

### ISSUE THREAD

**Issue by rheum** [joeyespo/sublimetext-console-exec#1]
Line 29 in console_exec.py uses "pause" command.

Use "read" instead on linux.

**Comment by joeyespo** [comment]
I don't spend a lot of time on Linux machines, so I initially intentionally didn't include Linux support.

Would changing `pause` to `read` be the only thing preventing this from working on Linux? If there aren't many changes required to get it to work, I'll gladly accept a pull request and then update the Readme.

**Comment by rheum** [comment]
Can't be much more than that. I'll send you a pull request, when I've fixed it.

Thanks a lot :)

**Comment by joeyespo** [comment]
Revisiting this project today. I'm getting it up on Package Control for ST2 and ST3.

Did you ever end up adding Linux support? If so, mind sharing what you did?

Thanks!

**Comment by joeyespo** [comment]
Actually, I went ahead and added the `read` fix, as well as using `;` so it always pauses. Mind [reviewing](https://github.com/joeyespo/sublimetext-console-exec/commit/452b00e0febe1976b8862691f2a9fc46b2df808f)?

Let me know if it still doesn't work for you!

**Comment by jfcherng** [comment]
`read` may not be available if BASH is not the default shell.

I just try this plugin on my Lubuntu 15.10 with TCSH as the default shell.
The console just blinks and gets `read: Command not found`.

**Comment by joeyespo** [comment]
@jfcherng Go figure. Any ideas?

And thanks for trying that out.

**Comment by jfcherng** [comment]
On my case, it seems that `xterm -e python3 -u /path/to/test.py ; read -p "Press [Enter] to continue..."` will be interpret as `xterm -e python3 -u test.py ;` and `read -p "Press [Enter] to continue..."`.
- `xterm -e python3 -u /path/to/test.py ;` runs in `xterm`.
- `read -p "Press [Enter] to continue..."` runs in a background process.

So currently, even if the default shell is BASH, `xterm` won't pause...
(I change my default shell to BASH and it doesn't pause.)

I am thinking that writing a script `pause.sh` like this:

```
#!/bin/env bash
read -p "Press [Enter] to continue..."
```

And construct this string `xterm -e "python3 -u /path/to/test.py ; bash '/path/to/pause.sh'"`
which makes `python3 -u /path/to/test.py ; bash '/path/to/pause.sh'` to be the command passed to `xterm`.
But `/path/to/test.py` may need to be escaped with backslash...

# 

By the way, on line 28 `pause = [';', 'read' '-p' '"Press [Enter] to continue..."']` misses two commas.
It's `pause = [';', 'read', '-p', '"Press [Enter] to continue..."']`, still not working, though.

**Comment by joeyespo** [comment]
Oh nice, I really like that solution. Do you think that could be run without the new file? Say, wrapped in `bash -c ""`? Or is `#!/bin/env bash` what's important here?

> misses two commas

Ugh! How'd that get by? Haha, thanks for pointing that out. Fixed in be1e38401a91b1ff0664c9a1582b8bd5605437c0.

**Comment by jfcherng** [comment]
`#!/bin/env bash` is not important here if the script is not used as an executable.
It states what executable should be used to run the script.
If we use `bash /path/to/the/script` rather than `./path/to /the/script`, it can be removed.

`bash -c "blablabla"` should work too.
But I am not sure will quotes make the escape complicated in `blablabla`.

**Comment by joeyespo** [comment]
Ok cool. Thanks for clarifying all of that.

> But I am not sure will quotes make the escape complicated

Yeah, that's why I didn't start out that way. Based on what you're saying, it'd be a good addition.

I just opened #4 for this. Want to take a shot at it?
