### ISSUE TITLE
Explicitly run `bash` on Linux so `read` is guaranteed to be used

### ISSUE THREAD

**Issue by joeyespo** [joeyespo/sublimetext-console-exec#4]
Opening a new issue from the conversation started in #1.

Probably the least invasive fix would be to encapsulate the `read` call in `bash -c ""`. (Just need to be careful when escaping that string.)

**Comment by jfcherng** [comment]
I have modified it to be usable on my environment (Lubuntu, TCSH).
Maybe we need someone else to test it.

https://github.com/jfcherng/sublimetext-console-exec/blob/9b0aaddb1357849973d8f9a829f98c694614b227/console_exec.py

**Comment by joeyespo** [comment]
Nice! Perhaps open a PR? That way we can start a discussion around it and possibly clean it up.

For example, it looks like `quote` is actually [deprecated in Python 2.7](https://docs.python.org/2/library/pipes.html), moving to a new package in 3.3. I wonder what else we can use.

What if we just inlined it instead?

``` python
pause = [';', 'bash', '-c', 'read -p "Press [Enter] to continue..."']
```

There's no user input, so manual escaping with `\"` should be ok. What do you think?

**Comment by joeyespo** [comment]
Just tested this locally and it seemed to work. Looks like Popen already knows how to quote args that contain spaces like `'read -p "Press [Enter] to continue..."'`.

**Comment by jfcherng** [comment]
quote() is deprecated in Python 2.7 but still exists at the bottom of [pipes.py](https://hg.python.org/cpython/file/2.7/Lib/pipes.py#l267).

Another solution is to copy its source codes out from Python 3.
The source code is located at https://hg.python.org/cpython/file/3.5/Lib/shlex.py#l278.

**Comment by joeyespo** [comment]
> but still exists at the bottom of pipes.py

This is true, however relying on deprecated or undocumented code like this usually leads to trouble later on. Copying and pasting isn't quite ideal either because now you're the one maintaining it.

In our case, Python won't be back-changing anything, so we could do something like:

``` python
try:
    from shlex import quote
except ImportError:
    from pipes import quote
```

Although I'd still rather see if we can simplify it all first.

I fixed the code in my comment a few min ago. Can you try out what's there now and see if that works for you?

**Comment by jfcherng** [comment]
In Python 3, `pipes.quote()` still works since pipes.py directly imports it from shlex.py.
See https://hg.python.org/cpython/file/3.3/Lib/pipes.py#l65.
So I think `from pipes import quote` is fine no matter Python>=3.3 or not.

**Comment by jfcherng** [comment]
On my machine, the following works.

``` python
        else:
            console = unix_console or ['xterm', '-e']
            # if a cmd list runs quote(), it's safe to do join()
            cmd = [quote(x) for x in cmd]
            pause = [';', 'bash', '-c', '\'read -p "Press [Enter] to continue..."\'']
            cmd = console + [' '.join(cmd + pause)]
```

**Comment by joeyespo** [comment]
Oh, I see. I had `xterm -e "{cmd}"; {pause}`, when we actually need `xterm -e "{cmd}; {pause}"` (the pause part _inside_ the `-e` string). And we're quoting `cmd` because otherwise a quote character would terminate the xterm argument.

Could it be simplified?

``` python
        else:
            console = unix_console or ['xterm', '-e']
            pause = '; bash -c "read -p \"Press [Enter] to continue...\""
            cmd = console + [quote(' '.join(cmd) + pause)]
```

I don't think each argument needs quoted, just the string as a whole. Or did I leave something out?

---

Also for reference, looks like `cmd` handles the `/c` argument quite differently:

> If /C or /K is specified, then the remainder of the command line after
> the switch is processed as a command line, where the following logic is
> used to process quote (") characters:
> 1.  If all of the following conditions are met, then quote characters
>       on the command line are preserved:
>    - no /S switch
>    - exactly two quote characters
>    - no special characters between the two quote characters,
>       where special is one of: &<>()@^|
>    - there are one or more whitespace characters between the
>       two quote characters
>    - the string between the two quote characters is the name
>       of an executable file.
> 2.  Otherwise, old behavior is to see if the first character is
>       a quote character and if so, strip the leading character and
>       remove the last quote character on the command line, preserving
>       any text after the last quote character.

There might be a bug on the Windows version too. I'll have to look into this more. Thanks for indirectly bringing that to my attention :-)

**Comment by jfcherng** [comment]
``` python
        else:
            console = unix_console or ['xterm', '-e']
            pause = '; bash -c "read -p \"Press [Enter] to continue...\""
            cmd = console + [quote(' '.join(cmd) + pause)]
```

In this case, `cmd` is not quoted.
Assuming we have `cmd = ["python3", "-u", "X``       `Y.py"]` which is passed from the `.build-settings`.
Now in the last line, `' '.join(cmd)` gives `python3 -u X`       `Y.py` which is not what we want.
(Because `X`       ``Y.py` becomes `X` and `Y.py`).
Thus,I think that every element in `cmd` should apply `quote()`.
`quote('ABC')` gives `ABC`!! No unnecessary quote is added here.

**Comment by joeyespo** [comment]
Ah, gotcha. You're right. `python -c "import sys;print sys.argv" "X  Y.py"` => `['-c', 'X  Y.py']` I was thinking the `X  Y.py` case would come in quoted for some reason.

`quote` seems to not add quotes when you don't need them either, which is a good feature of it.

Thanks for taking the time to explain this.

PR looks good!
