### ISSUE TITLE
Open the terminal depending on user's Desktop Environment.

### ISSUE THREAD

**Issue by jfcherng** [joeyespo/sublimetext-console-exec#6]
What do you think about making it detect users Desktop Environment and launch the corresponding terminal?

Code: https://gist.github.com/jfcherng/b18321a2c345fd1557b4

Gnome
![gnome](https://cloud.githubusercontent.com/assets/6594915/7953615/99152952-09f9-11e5-80eb-1208bb87d2d5.png)

KDE
![kde](https://cloud.githubusercontent.com/assets/6594915/7953626/bf053f80-09f9-11e5-9fc2-7b5c5d3f334f.png)

LXDE
![lxde](https://cloud.githubusercontent.com/assets/6594915/7953624/b6217a28-09f9-11e5-8c9a-1c12d7e73fe1.png)

Xterm
![xterm](https://cloud.githubusercontent.com/assets/6594915/7953654/1789ed36-09fa-11e5-9d0e-16a12b2dfc70.png)

Not finding a way to install XDE's terminal so there is no screenshot for it.

**Comment by joeyespo** [comment]
I'm open to is as long as it's straightforward. Such as running a known command or something similar to `import webbrowser; webbrowser.open('http://github.com')` but for terminals.

I don't think we should add a ton of custom cases though, because the number of terminals is unbounded, and could therefore compound the amount of code this project has.

Know of any single Unix commands or Python libraries that will "open the default terminal"?

**Comment by jfcherng** [comment]
A general method to get the default terminal is not found here.
I noticed that there is an `unix_console` option in the code,
so this enhancement may not be necessary to be implemented.

But in the current `HEAD` commit, adding an `unix_console` in `.build-settings` is not working.
This is probably caused by most terminal won't login a shell, so they don't know what is `;` and then abort the rest of commands after `;`.
(For Ubuntu, we may add `"unix_console": ["gnome-terminal", "-e"],` to test.)

---

In this post, I modified the code into the following to make the terminal always execution commands under `BASH`.

``` python
        else:
            console = unix_console or self.get_unix_console()
            pause = '; read -p "Press [Enter] to continue..."'
            escaped_cmd = ' '.join([quote(x) for x in cmd])
            console_cmd = console + ['bash -c ' + quote(escaped_cmd + pause)]
```

It works for customizing  an `unix_console` in `.build-settings`,
but I am not sure whether users' environment variable are passed or not.

---

Also found this: `xterm` is not a built-in terminal in MAC OSX.
Maybe another case for `os.name == 'XXX':`or `sublime.platform() == 'osx'`?

**Comment by joeyespo** [comment]
> I noticed that there is an unix_console option in the code, so this enhancement may not be necessary to be implemented.

Ok, excellent. I'd be open for a PR documenting this and the common cases that you've listed in the Readme. That's a good place for it.

I'm going to close this particular issue as "out of scope".

> so they don't know what is `;` and then abort the rest of commands

Interesting. Your code looks good. If you open a PR with that, you'll get the credit in the commit log :-) 

> but I am not sure whether users' environment variable are passed or not

We can cross that bridge when someone creates an issue needing it.

> Also found this: xterm is not a built-in terminal in MAC OSX

Oh I didn't realize that. I thought it would be available. Yeah, it'd probably be a good idea to make a case for `osx`.

Thanks for opening the issue, @jfcherng!
