### ISSUE TITLE
Console window flashes and quits

### ISSUE THREAD

**Issue by adieux** [joeyespo/sublimetext-console-exec#7]
I am using Windows 7 and after installation & build configuration, every time when I tried to compile & run a program, the console window flashes and quits. Any ideas? Thanks!

**Comment by joeyespo** [comment]
By "flashes" do you mean it pops up with a terminal window then immediately disappears?

**Comment by adieux** [comment]
Yes it flashes for half a sec and then disappears.

**Comment by joeyespo** [comment]
Interesting. Sounds like `cmd.exe` is running, so the script does complete.

Could you copy/paste your exact `Python.sublime-build` file?

Crazier thought. Can you go to Start, Run, and run `cmd.exe` and try running `pause` manually? Pause is the command that keeps the window open.

**Comment by adieux** [comment]
Thanks! 

Firstly I tried to use pause for my terminal and the problem is still there. 

My Python.sublime-build originally is:

```
{
    "shell_cmd": "python -u \"$file\"",
    "file_regex": "^[ ]*File \"(...*?)\", line ([0-9]*)",
    "selector": "source.python",
    "variants":
    [
        {
            "name": "Syntax Check",
            "shell_cmd": "python -m py_compile \"${file}\"",
        }
    ]
}
```

How can I modify it?

**Comment by joeyespo** [comment]
Ok. Looks like there's a few issues here:
- You don't have `"target": "console_exec"` in your example
- The `console_exec` plugin uses `cmd` to get the command to run, not `shell_cmd` (the missing `cmd` might be why it flashes without calling pause)
- The `variants` here is unnecessary. Python will automatically syntax-check the file when it runs

Try replacing what you have with this:

```
{
    "cmd": ["python", "-u", "$file"],
    "file_regex": "^[ ]*File \"(...*?)\", line ([0-9]*)",
    "selector": "source.python",
    "target": "console_exec"
}
```

**Comment by adieux** [comment]
This fixed the issue! 

I used to have <code>"target": "console_exec"</code> in my configuration, and I deleted the <code>variants</code>. But it still didn't work. 

When I changed  <code>shell_cmd</code> to <code>cmd</code> , that solved it! 

Thanks a lot!!!

**Comment by joeyespo** [comment]
No problem! Glad I could help :-)
